<?php

use Drupal\Core\Form\FormStateInterface;

/**
 * hook_form_alter
 *
 * @param $form
 * @param \Drupal\Core\Form\FormStateInterface $form_state
 * @param $form_id
 */
 function alterlogin_form_alter(&$form, FormStateInterface $form_state, $form_id) {

  if ($form_id == 'user_login_form') {
    $form['captcha'] = [
      '#type' => 'html_tag',
      '#tag' => 'bits-captcha',
      '#attributes' => [
        'data-form-id' => 'user-login-form',
        'data-form-reset' => 'false',
      ],
      '#attached' => [
        'library' => [
          'alterlogin/alterlogin',
        ],
      ],
    ];
  }
}
